### ISSUE TITLE
Doesn't show up in safari extensions anymore

### ISSUE THREAD

**Issue by glottis0q** [smmr-software/privacy-redirect-safari#13]
<img width="904" alt="142980561-0dbf79a0-16ba-4679-99b6-b70f97357f8f" src="https://user-images.githubusercontent.com/93644977/142980634-e6a16de1-854e-401b-8d67-8167e040ac1b.png">
<img width="962" alt="142980541-eec58657-30f3-488a-8059-e291a0dbb21f" src="https://user-images.githubusercontent.com/93644977/142980635-2cdc5831-2592-4c9c-b3a9-77f3cf651131.png">

**Comment by acrostich** [comment]
Same problem happening on Safari Version 15.1 (16612.2.9.1.30, 16612) running on macOS Big Sur Version 11.6.1 (20G224).

Also the 'Open Safari Extension Preferences' button in the app doesn't work. i.e. pressing it does nothing. The app correctly identifies that 'The extension is currently disabled.'

**Comment by glottis0q** [comment]
I uninstalled it, created a new mac user and reinstalled it. Works again. I dont know if its worth the effort for you though.

**Comment by acrostich** [comment]
It seems to be due to a Safari bug. The solution sugggested by/for WIPR worked for me for Privacy Redirect as well: https://giorgiocalderolla.com/wipr-faq.html#wipr-extra-is-missing

**Comment by FIGBERT** [comment]
@acrostich good find! I'm going to close this issue now, and I'll add something about this to the README to let people know what's up if they encounter this issue in the future.
