### ISSUE TITLE
Wikipedia support

### ISSUE THREAD

**Issue by jobukkit** [smmr-software/privacy-redirect-safari#14]
Besides Wikiless which the original Privacy Redirect supports, I would love support for [V for Wiki](https://v-for-wiki.com), a great Wikipedia client for iOS. So `https://en.wikipedia.org/wiki/Chocolate` would redirect to `v-for-wiki://article/en/Chocolate`.

**Comment by FIGBERT** [comment]
Unfortunately, I do not believe we will be implementing Wikipedia redirects at this time.

Some of the team's thoughts for context:
> The other supported redirects take someone away from a malicious (advertising, other such corporate spying), javascript-bloated websites and towards a more privacy-respecting, minimalist front-end. Wikipedia doesn't have the same problems.

> The Wikiless project's main reasons given for existing seem a bit misguided, and are centered around IP-related issues best solved through other means. If you're circumventing Wikipedia censorship in your nation, you should use Tor (probably with a bridge). If you'd like to prevent Wikipedia from getting your IP address, you should use a VPN.
