### ISSUE TITLE
Reddit needs www.reddit.com

### ISSUE THREAD

**Issue by rnkn** [smmr-software/privacy-redirect-safari#16]
Hello,

In order for Reddit to redirect, the `www.reddit.com` domain is needed (because `reddit.com` already redirects to `www.reddit.com`).

Thanks!

**Comment by FIGBERT** [comment]
I do believe we already request access to `www.reddit.com`.

:)

**Comment by rnkn** [comment]
Negative. Navigating to `reddit.com` or `www.reddit.com` will not redirect:

<img width="1440" alt="Screen Shot 2022-01-01 at 3 40 37 pm" src="https://user-images.githubusercontent.com/1256849/147844724-522adfd9-2d28-4e39-a591-2f5982f568a0.png">

I mean, you probably could have checked this before closing the issue? Just saying...

**Comment by FIGBERT** [comment]
I mean, I checked it on my setup! Are reddit->teddit redirects enabled?

**Comment by rnkn** [comment]
Ha sorry my man, NYE hangover has me a bit crabby.

So I have it fixed but I it's a bit weird. All system are go:

<img width="703" alt="Screen Shot 2022-01-01 at 4 11 58 pm" src="https://user-images.githubusercontent.com/1256849/147845113-3d6625b4-209b-4d17-b7e0-11764bd71f05.png">

I had initially set all websites to "Allow" in the preference pane, but what fixed it was: I visited reddit, then clicked the toolbar button and clicked always allow in the pop-over. Then it redirected to teddit.

So it's fixed for my uses (issue closable) but maybe there's something fishy with the way it saves settings via the preference pane?

Happy 2022 :)

**Comment by FIGBERT** [comment]
Yeah not sure what's up with that... Safari can be weird with extensions in general, so not sure if there's a fix to be implemented on my end. Glad you've got it working!

**Comment by FIGBERT** [comment]
Oh also happy 2022 duh
