### ISSUE TITLE
remove 'for safari' from extension name

### ISSUE THREAD

**Issue by hellojaccc** [smmr-software/privacy-redirect-safari#19]
![image](https://user-images.githubusercontent.com/71537512/150787258-6bf3e897-5606-424e-b825-f5731b151993.jpeg)

Extension name is too long that it makes menu(?) too big

**Comment by rnkn** [comment]
Lol I came here to suggest this too! It's tautologous anyway -- a Safari extension for Safari 🤔

**Comment by FIGBERT** [comment]
The pleonasm has been remedied in 8bf7839!

**Comment by rnkn** [comment]
I guess this hasn't made it to the App Store versions yet?

**Comment by FIGBERT** [comment]
My backpack was stolen a few weeks back, and with it my Mac laptop. Currently running from my backup Void Linux machine, so I'm not able to submit new builds to the App Store.

I did, however, just place an order for a new Mac and thus will have a new version up ASAP. The update will indeed be long overdue. Just some hectic circumstances going on over here.

**Comment by rnkn** [comment]
Oh damn, that sucks. Sorry to hear. Hopefully the thief gets a dose of karma.

**Comment by FIGBERT** [comment]
Updates have been submitted! iOS has been approved, macOS was rejected and resubmitted with a slight edit to the update message.

**Comment by FIGBERT** [comment]
and macOS is live! enjoy the updates.
