### ISSUE TITLE
Add FOSS Wikipedia front end Wikiless.org?

### ISSUE THREAD

**Issue by garth-xmr** [smmr-software/privacy-redirect-safari#26]
https://wikiless.org/ - Official instance

Community instances:

https://wikiless.alefvanoon.xyz/
https://wikiless.sethforprivacy.com/ + [hidden server](http://dj2tbh2nqfxyfmvq33cjmhuw7nb6am7thzd3zsjvizeqf374fixbrxyd.onion/)
https://wiki.604kph.xyz/

**Comment by FIGBERT** [comment]
We addressed the addition of Wikiless in issue #14. [We will not be implementing it at this time.](https://github.com/smmr-software/privacy-redirect-safari/issues/14#issuecomment-1007159101)
