### ISSUE TITLE
Allow Search Engine Redirection for Others

### ISSUE THREAD

**Issue by httpjamesm** [smmr-software/privacy-redirect-safari#28]
Currently, the Search Engine Redirects option only works with Google. This could be used to choose "custom" search engine within Safari, as all Google queries would be auto redirected to a search engine of your choice. However, due to Safari limitations, Google would still get your query, autocomplete queries and browser data. 

The solution could be to add an option that redirects all search engines, like DuckDuckGo, so users can choose a "custom" search engine with this feature without sending data to Google by default.

**Comment by lothar-cell** [comment]
I also would like to see redirect from DuckDuckGo to Startpage.
