### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Mennaruuk** [smmr-software/privacy-redirect-safari#29]
Hey! Just wanted to report some broken links I noticed [here](https://github.com/smmr-software/privacy-redirect-safari/blob/1c218927aaf839d9107e12b065c2adc96bd46014/Shared%20(App)/Instances.swift):

translate.metalune.xyz (maintenance is ceased)
whoogle.himiko.cloud (site is dead)

Thanks!

**Comment by FIGBERT** [comment]
Thanks for the heads up!
