### ISSUE TITLE
Google Meet redirected to OpenStreetMaps

### ISSUE THREAD

**Issue by Rjevski** [smmr-software/privacy-redirect-safari#3]
`https://meet.google.com/*` was for some reason redirected to OpenStreetMaps - I will do more testing later on but I've had to temporarily disable the add-on so I could join a meeting.

**Comment by FIGBERT** [comment]
What has additional testing produced? Not sure how this could happen, as the `manifest.json` file does not request access to `https://meet.google.com/*`:

https://github.com/smmr-software/privacy-redirect-safari/blob/ad441b6886e0231f0889f53e9bf94bd8046667c5/Privacy%20Redirect%20for%20Safari%20Extension/manifest.json#L35-L41

See: [Match pattern docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns)

**Comment by Rjevski** [comment]
I believe Safari doesn't implement the `permissions` property as per the spec you listed - it seems like a permission for a top-level domain immediately gives it permissions for any and all subdomains, which is worrying but not necessarily critical. However, what seems like a proper and serious bug is that in the dev console it looks like the scripts for Google Translate, Google Maps and Search are all invoked too - here's a screenshot of the developer console when attempting to open Google Meet:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45625150/130370357-e4f32a0f-1e85-486f-aa68-238dd029af38.png">

This seems to only happen when the `google.com` domain permission (in Safari Preferences -> Websites -> Extensions -> Privacy Redirect) is set to "allow" while `maps.google.com`, `search.google.com` and `translate.google.com` are set to Ask. This happens automatically if you set `google.com` to "deny" (and then doesn't change back if you change it back to allow).

I am running Safari 14.1.2.

**Comment by FIGBERT** [comment]
I see two options (which are not mutually exclusive):
1. We can debug the Safari `permissions` stuff so that it only works on intended domains
2. We can add a check to the JavaScript that ensures it only runs on the intended domain.

I've got to look more into replicating this, first of all – I've been quite busy as of late. I'm going to look into both options for now.

**Comment by jneplokh** [comment]
@Rjevski I seem to be unable to replicate this (even after setting the "allow" and "ask" settings described. Does it still occur?

Thanks!

**Comment by FIGBERT** [comment]
As there's been no update on the matter, and we have not been able to replicate this, I'm going to close this issue for now.
