### ISSUE TITLE
Custom instances: allow http protocol

### ISSUE THREAD

**Issue by isker** [smmr-software/privacy-redirect-safari#30]
Hi.  Thanks for this app.

I self host instances of various services that I’d like to redirect to.  But these instances are exposed only over http, and the redirect assumes https.  It is not possible to reach my instances:  it seems that https is unconditionally prepended when redirecting.

(http is acceptable for me as my instances are not exposed to the internet and are reachable only via WireGuard tunneling, which provides the actual handshake/encryption.)

The upstream browser extension this project is forked from does not have this issue; I can configure http redirects there.

**Comment by isker** [comment]
Ah, it seems from https://github.com/smmr-software/privacy-redirect-safari/search?q=https&type= that the protocol is not configured at all and each of the scripts just hard codes https.  Welp, that makes this a bit more work…

**Comment by FIGBERT** [comment]
Done! Have fun with WireGuard!

**Comment by isker** [comment]
Thanks!  Looking forward to the release.

**Comment by isker** [comment]
It works!  Thanks!
