### ISSUE TITLE
[Question] [iOS] Instance names on configuration page

### ISSUE THREAD

**Issue by Ozymandias117** [smmr-software/privacy-redirect-safari#32]
With the addition of TikTok and Imgur under the platform names, with instances available under the dropdown, it started making me think it would make more sense for all redirects main title to be the platform name?

I'm sure most new users or people trying to improve their privacy will be able to guess "Nitter -> Twitter," and "Teddit or Libreddit" -> "Reddit" (however, in this case, there's also an option of old.reddit.com). However a new user would probably see "Invidious" -> "???"

It seems like standardizing on the proprietary platform being redirected away from would both make it easier for new users, and allow all instances that you believe are a better alternative to be offered under the same setting.

**Comment by Ozymandias117** [comment]
It is on the main page:
https://github.com/smmr-software/privacy-redirect-safari/blob/a0085d35659f828bdbb0ee819a411f22c5f6336c/iOS%20(App)/ContentView.swift#L81

But not on the configuration page, a. la:
https://github.com/smmr-software/privacy-redirect-safari/blob/a0085d35659f828bdbb0ee819a411f22c5f6336c/iOS%20(App)/InstancesView.swift#L60

**Comment by FIGBERT** [comment]
I'd been thinking about this for a minute, but never got around to actually fixing it. Going to standardize around the service we're redirecting *from* (i.e. Reddit) as opposed to the frontend we're going *to*, as there may be multiple (i.e. Teddit or Libreddit). Should be cleaner.
