### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by narFnarF** [smmr-software/privacy-redirect-safari#35]
I can't make it work. It never redirects. I'm guessing I'm doing something wrong but I can't find what.

**Comment by narFnarF** [comment]
If I visit a website with an embedded YouTube video, it isn't redirected. 

If I click to open this video on YouTube, it's not redirected either. 

I tried visiting a Twitter profile: no redirect.

**Comment by narFnarF** [comment]
I'm using Safari of course. 

And in the Privacy Redirect app, I activated all options.

**Comment by FIGBERT** [comment]
You're going to have to allow Privacy Redirect to access the sites you're visiting for redirects to work. The first time you visit a site like Twitter, you'll need to click on the `Aa` menu and then Privacy Redirect and give it permission to act on all sites.

**Comment by FIGBERT** [comment]
Closing due to lack of response.

**Comment by narFnarF** [comment]
The problem was that the extension was not visible in the `Aa` menu, because I have other extensions installed and Safari doesn't make it clear that we can scroll in this menu. 

Hopefully this information can help others in the future.

**Comment by narFnarF** [comment]
That being said, even after activating it (and selecting "always" and "all websites", it still doesn't redirect YouTube or Twitter...

**Comment by FIGBERT** [comment]
May be related to #31, we're investigating.
