### ISSUE TITLE
Doesn't work on Google sites other than google.com

### ISSUE THREAD

**Issue by jeifour** [smmr-software/privacy-redirect-safari#4]
This works

https://www.google.com/maps/place/HBS+Hessische+Bewehrungsstahl+GmbH/@50.0466822,8.4837444,17z/data=!4m5!3m4!1s0x47bda032b1630ac9:0xff42c97a9a179a88!8m2!3d50.0473184!4d8.4850227?shorturl=1
https://www.google.com/search?q=recursion&client=safari

but this doesn't

https://www.google.de/maps/place/HBS+Hessische+Bewehrungsstahl+GmbH/@50.0466822,8.4837444,17z/data=!4m5!3m4!1s0x47bda032b1630ac9:0xff42c97a9a179a88!8m2!3d50.0473184!4d8.4850227?shorturl=1
https://www.google.de/search?q=recursion&client=safari
https://translate.google.de/?sl=auto&tl=ja&text=Hallo&op=translate

Maybe you want to consider also redirecting for the biggest country-specific Google sites? Not sure if redirecting every single one is easily feasible because there are so many.

**Comment by FIGBERT** [comment]
As an occasional google.co.il user myself, I can sympathize – I think all this would require would be some changes to the `manifest.json` adding the proper localized domains.

The main challenge is the sheer quantity of localized TLDs. Is there a list somewhere of all localized Google domains?

**Comment by jeifour** [comment]
> Is there a list somewhere of all localized Google domains?

This should be a good source: https://www.google.com/supported_domains
