### ISSUE TITLE
Youtube redirections to Invidious not working

### ISSUE THREAD

**Issue by gauffke** [smmr-software/privacy-redirect-safari#42]
Hi All,

Using iOS15.5 with all updates to this day (22 Jun 2022).
Enabled redirection for all services in the iOS app.
Enabled the extension from Preferences > Safari > Extensions
Enabled it within Safari (Aa > "Privacy Redirect for Safari" shows a blue earth logo)
Still, going to youtube.com or search for "youtube.com ACDC" in Duckduckgo still brings me to m.youtube.com/user/acdc
Clicking on a video link gives me:
1. A pop up: Do you want to download "watch"?
2. Keeps the youtube.com window, with an empty screen (1/3 top is black, 2/3 low is white) and a circling icon in the middle

Important to note that despite working for Nitter, Teddit, ... Opening the app still tells me "Enable the extension in Safari Settings" (which is done).

Phone reboot did not change anything.

Am I doing something wrong, or is it a known issue?

Thanks!

**Comment by FIGBERT** [comment]
The "Do you want to download 'watch'" prompt is a problem with [invidious.snopyta.org](https://invidious.snopyta.org/). We've removed them as a default in iOS v1.4.3, which... we haven't released yet. Check and see if switched your instance fixes the issue.

If this does work, let me know and I'll close the issue.

**Comment by gauffke** [comment]
Confirmed that a change of instance to yewtu.be indeed works!

a final one: does it make sense that the app always shows « Enable the extension in Safari Settings » (which is done)?

**Comment by FIGBERT** [comment]
Glad the yewtu.be switch worked. We'll push the update changing the default instance out in the next couple days.

> does it make sense that the app always shows « Enable the extension in Safari Settings »

Well, not really, but unfortunately the [mechanism for checking extension state](https://developer.apple.com/documentation/safariservices/sfsafariextensionmanager/2122754-getstateofsafariextension) is only available on macOS. Such is the fun of working with Apple platforms.
