### ISSUE TITLE
Add redirects for Quora, IMDB, and Fandom.

### ISSUE THREAD

**Issue by catwithbanana** [smmr-software/privacy-redirect-safari#48]
Redirects for Quora (Quetre), IMDB (LibremDB), and Fandom (BreezeWiki) were recently added to the LibRedirect extension. All three frontends are cleaner and faster to load than the sites they replace.

Could they get added to Privacy Redirect Safari as well?

Thanks!

**Comment by Samlane86** [comment]
I came to request Libremdb too! But I’ll just second this request.

**Comment by FIGBERT** [comment]
I've added support for Quora and IMDB redirects on the `main` branch. I'm going to wait until tomorrow, with the release of macOS Ventura, to build the app with the new Xcode and send the release to Apple.

Fandom redirects are a little more complicated. As the extension is currently structured, we have to list every domain we want to run the respective redirects on. Each Fandom wiki has its own subdomain, right? Is there a list of all of them somewhere?

**Comment by Samlane86** [comment]
> I've added support for Quora and IMDB redirects on the `main` branch. I'm going to wait until tomorrow, with the release of macOS Ventura, to build the app with the new Xcode and send the release to Apple.
> 

Thank you so much for the quick response! I’m on an iPhone, so I’ll forward to seeing the additions tomorrow!

**Comment by Samlane86** [comment]
I saw that IMDb is incorporated into the iOS app now. Thanks for adding support for that! The only thing I noticed in testing it is it doesn’t redirect links to the mobile version of IMDb. Could you add m.IMDb.com to the permissions settings?
Thanks again!
Sam

**Comment by catwithbanana** [comment]
A toggle for mobile versions would be ideal, since desktop versions work better on iPad.

**Comment by FIGBERT** [comment]
Mobile IMDB redirects are live with today's hot fix. Going to close this issue, and leave Fandom redirects for another time. We've been running up against some of the fundamental limitations of the APIs, and have to think about where to go from here on those issues.
