### ISSUE TITLE
Bibliogram / Instagram support

### ISSUE THREAD

**Issue by jeifour** [smmr-software/privacy-redirect-safari#5]
https://github.com/SimonBrazell/privacy-redirect already has it, so would be nice to get it.

**Comment by FIGBERT** [comment]
This was one of our initial goals, but unfortunately we've determined it's not possible to implement currently.

Simon Brazell's project uses the `webRequest.onBeforeRequest` API to intercept requests before they're sent and modify them to go to frontends like Bibliogram. Safari's limited support for the `onBeforeRequest` API means that we can't do this, so we have to redirect users as soon as the page loads.

Instagram, however, immediately redirects to a login page when trying to view a post from the desktop – and we can't redirect to Bibliogram before that happens.

Obviously, we'll keep our eye out for any changes in this area.

**Comment by jeifour** [comment]
Understandable. Thanks for the fast reaction to my issue.

**Comment by FIGBERT** [comment]
> Understandable. Thanks for the fast reaction to my issue.

Tbh I am bored at school, and I'm so happy to have people interacting with a project of mine.

> (Btw, the TLS certificate that the webserver reachable on https://smmr.software serves has been invalid for a week now.)

I've been looking into that for the past few days. Just figured it out, should be fixed now.

**Comment by jobukkit** [comment]
Instagram does not immediately redirect to a login page for me. Did they change this in the last few months? If so, Instagram support should now be possible. (Though Bibliogram is kinda spotty due to Instagram blocking instances...)
