### ISSUE TITLE
Startpage and IMDB redirects don't work on iOS

### ISSUE THREAD

**Issue by lothar-cell** [smmr-software/privacy-redirect-safari#51]
Startpage works only very rarely (using Safari search/address bar)
IMDB redirect - I couldn't get a single one

They work on MacOS. Maybe the problem is with m.sites?

**Comment by FIGBERT** [comment]
IMDB redirects on mobile should be fixed in today's hotfix.

With regard to Startpage redirects, what search engine are you using? Could you give me an example (a search URL that doesn't redirect)?

**Comment by lothar-cell** [comment]
Thanks for the hotfix. 
I use built in DuckDuckGo, but now for example the first couple of tries worked, after that none: https://duckduckgo.com/?q=example&t=iphone&ia=definition
