### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by lothar-cell** [smmr-software/privacy-redirect-safari#53]
I'm wondering because there hasn't been any meaningful update for a while now, and it's lacking features compared to _free_ alternatives on Firefox.

**Comment by FIGBERT** [comment]
The project is alive—I use it every day! Quite happy with the state of it.

If there are any issues or missing features that come to bother me too much, they'll get implemented. Others are free to do the same; this is open-source, so PRs are welcome.

**Comment by lothar-cell** [comment]
Ah, I didn't know this project is for you. Now it makes sense.
