### ISSUE TITLE
Suggestion: iOS / iPadOS 15 Extension

### ISSUE THREAD

**Issue by 31j** [smmr-software/privacy-redirect-safari#6]
Good afternoon! 

I have yet to read into the documentation on this at all so I couldn't really tell you the feasibility of this (apologies), however if it is a relatively hassle free process it would be quite nice to have privacy redirect be compatible with the new extensions support on mobile safari. At this point there is mostly content blockers / dark mode extensions, so it would be nice to see other extensions (such as this one) be available :)

**Comment by FIGBERT** [comment]
That's been part of my plans for a while. Going to get on that sometime soon – perhaps tonight.

**Comment by 31j** [comment]
I’m not sure the proper nomenclature on iOS for this, so I will use terms relevant to android for the same concept + screenshots. But it seems like extensions are unable to do anything on “custom tab intents” when a hyperlink is clicked in an app, I’m just mentioning since I could see this presenting a problem. Would the extensions still be able to use ``onBeforeRequest`` in the app that invoked safari? Or would it only be able to when you hit the button to reopen the tab in a dedicated Safari tab (which usually seems to reload the page anyways) 
![D24B8BEC-32D1-462B-8C9D-EE6899E6593B](https://user-images.githubusercontent.com/32624322/134353389-1250a5c2-b6c1-47e0-b103-ee8c2d015975.jpeg)
![B44BEA02-FBC8-44FA-94FE-F5EFADD0D57D](https://user-images.githubusercontent.com/32624322/134353391-899de1f2-8dbf-465e-89c5-0f3fa887e7d0.png)
