### ISSUE TITLE
Medium / Scribe support

### ISSUE THREAD

**Issue by jeifour** [smmr-software/privacy-redirect-safari#7]
Pretty self-explanatory, but this is a suggestion to add support for Medium redirections to Scribe. See for more details: https://scribe.rip / https://git.sr.ht/~edwardloveall/scribe

**Comment by FIGBERT** [comment]
This sounds like a great idea – always fun to see new front-ends pop up. Probably going to be implemented after #6 is finished, as that involves a great deal of refactoring (see the `ios` branch for more).

**Comment by rnkn** [comment]
Yes please. Medium is the devil.
